package com.mai.greendaox;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.mai.annotate.Column;
import com.mai.annotate.Id;
import com.mai.annotate.Table;

import java.util.Arrays;
import java.util.Date;

@Table(name = "device")
public class Device {

    @Column
    private java.util.Date testDate;

    @Column
    private Boolean testBoolean;

    @Id(autoIncrement = true)
    private Long testLong;

    @Column
    private byte[] testByteArray;
    @Column
    private byte testByte;
    @Column
    private Double testDouble;
    @Column
    private Float testFloat;
    @Column(unique = true)
    private int testInt;
    @Column
    private Short testShort;

    @Column
    private String testString;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Device() {
    }


    public Date getTestDate() {
        return testDate;
    }

    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    public Boolean getTestBoolean() {
        return testBoolean;
    }

    public void setTestBoolean(Boolean testBoolean) {
        this.testBoolean = testBoolean;
    }

    public Long getTestLong() {
        return testLong;
    }

    public void setTestLong(Long testLong) {
        this.testLong = testLong;
    }

    public byte[] getTestByteArray() {
        return testByteArray;
    }

    public void setTestByteArray(byte[] testByteArray) {
        this.testByteArray = testByteArray;
    }

    public byte getTestByte() {
        return testByte;
    }

    public void setTestByte(byte testByte) {
        this.testByte = testByte;
    }

    public Double getTestDouble() {
        return testDouble;
    }

    public void setTestDouble(Double testDouble) {
        this.testDouble = testDouble;
    }

    public Float getTestFloat() {
        return testFloat;
    }

    public void setTestFloat(Float testFloat) {
        this.testFloat = testFloat;
    }

    public int getTestInt() {
        return testInt;
    }

    public void setTestInt(int testInt) {
        this.testInt = testInt;
    }

    public Short getTestShort() {
        return testShort;
    }

    public void setTestShort(Short testShort) {
        this.testShort = testShort;
    }

    public String getTestString() {
        return testString;
    }

    public void setTestString(String testString) {
        this.testString = testString;
    }

    @Override
    public String toString() {
        return "Device{" +
                "testDate=" + testDate +
                ", testBoolean=" + testBoolean +
                ", testLong=" + testLong +
                ", testByteArray=" + Arrays.toString(testByteArray) +
                ", testByte=" + testByte +
                ", testDouble=" + testDouble +
                ", testFloat=" + testFloat +
                ", testInt=" + testInt +
                ", testShort=" + testShort +
                ", testString='" + testString + '\'' +
                '}';
    }
}
